[2021-04-28 02:31:58 DEBUG] [cli:73] ###############################################################################
[2021-04-28 02:31:58 DEBUG] [cli:74] Running command 'run'
[2021-04-28 02:31:58 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-28 02:31:58 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-28 02:31:58 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:31:58 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:31:58 ERROR] [cli:164] Path "chaos/termpod1" does not exist.
[2021-04-28 02:31:58 DEBUG] [cli:165] Path "chaos/termpod1" does not exist.
[2021-04-28 02:32:45 DEBUG] [cli:73] ###############################################################################
[2021-04-28 02:32:45 DEBUG] [cli:74] Running command 'run'
[2021-04-28 02:32:45 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-28 02:32:46 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-28 02:32:46 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:32:46 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:32:46 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:32:46 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:32:46 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-28 02:32:46 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:32:46 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:32:46 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:32:47 INFO] [experiment:96] Experiment looks valid
[2021-04-28 02:32:47 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:32:47 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:32:47 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:32:47 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:32:47 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:32:47 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:32:47 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-28 02:32:47 DEBUG] [__init__:39] Initializing controls
[2021-04-28 02:32:47 INFO] [run:342] Steady-state strategy: default
[2021-04-28 02:32:47 INFO] [run:345] Rollbacks strategy: default
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:32:47 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-28 02:32:47 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:47 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:32:47 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:32:47 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:32:47 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:32:47 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:47 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:32:47 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:32:47 INFO] [run:553] Playing your experiment's method now...
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:47 INFO] [activity:161] Action: terminate-app-pod
[2021-04-28 02:32:47 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-28 02:32:47 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:32:47 DEBUG] [actions:193] Found 1 pods labelled 'app=productpage' in ns default
[2021-04-28 02:32:47 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:32:47 DEBUG] [run:496] Running steady-state hypothesis after the method
[2021-04-28 02:32:47 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:47 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:32:47 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:32:47 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:32:47 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:32:47 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:47 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:32:47 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:32:47 INFO] [run:809] Let's rollback...
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:32:47 INFO] [rollback:25] No declared rollbacks, let's move on.
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:32:47 INFO] [run:421] Experiment ended with status: completed
[2021-04-28 02:32:47 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:32:47 DEBUG] [__init__:72] Cleaning up controls
[2021-04-28 02:32:47 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:32:54 DEBUG] [cli:73] ###############################################################################
[2021-04-28 02:32:54 DEBUG] [cli:74] Running command 'run'
[2021-04-28 02:32:54 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-28 02:32:55 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:32:55 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:32:55 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:32:55 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-28 02:32:55 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:32:55 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:32:55 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:32:55 INFO] [experiment:96] Experiment looks valid
[2021-04-28 02:32:55 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:32:55 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:32:55 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:32:55 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:32:55 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:32:55 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:32:55 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-28 02:32:55 DEBUG] [__init__:39] Initializing controls
[2021-04-28 02:32:55 INFO] [run:342] Steady-state strategy: default
[2021-04-28 02:32:55 INFO] [run:345] Rollbacks strategy: default
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:32:55 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-28 02:32:55 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:55 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:32:55 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:32:55 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:32:55 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:32:55 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:55 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:32:55 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:32:55 INFO] [run:553] Playing your experiment's method now...
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:55 INFO] [activity:161] Action: terminate-app-pod
[2021-04-28 02:32:55 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-28 02:32:55 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:32:55 DEBUG] [actions:193] Found 2 pods labelled 'app=productpage' in ns default
[2021-04-28 02:32:55 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:32:55 DEBUG] [run:496] Running steady-state hypothesis after the method
[2021-04-28 02:32:55 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:55 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:32:55 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:32:55 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:32:55 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:32:55 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:32:55 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:32:55 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:32:55 INFO] [run:809] Let's rollback...
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:32:55 INFO] [rollback:25] No declared rollbacks, let's move on.
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:32:55 INFO] [run:421] Experiment ended with status: completed
[2021-04-28 02:32:55 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:32:55 DEBUG] [__init__:72] Cleaning up controls
[2021-04-28 02:32:55 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:33:00 DEBUG] [cli:73] ###############################################################################
[2021-04-28 02:33:00 DEBUG] [cli:74] Running command 'run'
[2021-04-28 02:33:00 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-28 02:33:00 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-28 02:33:00 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:33:00 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:33:00 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:33:00 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:33:00 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-28 02:33:00 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:33:00 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:33:00 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:33:01 INFO] [experiment:96] Experiment looks valid
[2021-04-28 02:33:01 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:33:01 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:33:01 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:33:01 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:33:01 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:33:01 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:33:01 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-28 02:33:01 DEBUG] [__init__:39] Initializing controls
[2021-04-28 02:33:01 INFO] [run:342] Steady-state strategy: default
[2021-04-28 02:33:01 INFO] [run:345] Rollbacks strategy: default
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:33:01 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-28 02:33:01 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:01 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:33:01 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:33:01 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:01 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:33:01 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:01 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:33:01 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:01 INFO] [run:553] Playing your experiment's method now...
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:01 INFO] [activity:161] Action: terminate-app-pod
[2021-04-28 02:33:01 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-28 02:33:01 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:01 DEBUG] [actions:193] Found 2 pods labelled 'app=productpage' in ns default
[2021-04-28 02:33:01 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:33:01 DEBUG] [run:496] Running steady-state hypothesis after the method
[2021-04-28 02:33:01 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:01 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:33:01 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:33:01 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:01 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:33:01 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:01 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:33:01 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:01 INFO] [run:809] Let's rollback...
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:33:01 INFO] [rollback:25] No declared rollbacks, let's move on.
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:33:01 INFO] [run:421] Experiment ended with status: completed
[2021-04-28 02:33:01 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:33:01 DEBUG] [__init__:72] Cleaning up controls
[2021-04-28 02:33:01 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:33:10 DEBUG] [cli:73] ###############################################################################
[2021-04-28 02:33:10 DEBUG] [cli:74] Running command 'run'
[2021-04-28 02:33:10 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-28 02:33:11 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-28 02:33:11 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:33:11 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:33:11 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:33:11 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:33:11 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-28 02:33:11 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:33:11 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:33:11 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:33:12 INFO] [experiment:96] Experiment looks valid
[2021-04-28 02:33:12 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:33:12 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:33:12 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:33:12 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:33:12 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:33:12 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:33:12 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-28 02:33:12 DEBUG] [__init__:39] Initializing controls
[2021-04-28 02:33:12 INFO] [run:342] Steady-state strategy: default
[2021-04-28 02:33:12 INFO] [run:345] Rollbacks strategy: default
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:33:12 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-28 02:33:12 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:12 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:33:12 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:33:12 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:12 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:33:12 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:12 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:33:12 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:12 INFO] [run:553] Playing your experiment's method now...
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:12 INFO] [activity:161] Action: terminate-app-pod
[2021-04-28 02:33:12 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-28 02:33:12 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:12 DEBUG] [actions:193] Found 3 pods labelled 'app=productpage' in ns default
[2021-04-28 02:33:12 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:33:12 DEBUG] [run:496] Running steady-state hypothesis after the method
[2021-04-28 02:33:12 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:12 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:33:12 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:33:12 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:12 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:33:12 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:12 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:33:12 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:12 INFO] [run:809] Let's rollback...
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:33:12 INFO] [rollback:25] No declared rollbacks, let's move on.
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:33:12 INFO] [run:421] Experiment ended with status: completed
[2021-04-28 02:33:12 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:33:12 DEBUG] [__init__:72] Cleaning up controls
[2021-04-28 02:33:12 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:33:18 DEBUG] [cli:73] ###############################################################################
[2021-04-28 02:33:18 DEBUG] [cli:74] Running command 'run'
[2021-04-28 02:33:18 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-28 02:33:19 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:33:19 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:33:19 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:33:19 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-28 02:33:19 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:33:19 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:33:19 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:33:19 INFO] [experiment:96] Experiment looks valid
[2021-04-28 02:33:19 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:33:19 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:33:19 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:33:19 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:33:19 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:33:19 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:33:19 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-28 02:33:19 DEBUG] [__init__:39] Initializing controls
[2021-04-28 02:33:19 INFO] [run:342] Steady-state strategy: default
[2021-04-28 02:33:19 INFO] [run:345] Rollbacks strategy: default
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:33:19 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-28 02:33:19 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:19 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:33:19 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:33:19 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:19 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:33:19 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:19 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:33:19 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:19 INFO] [run:553] Playing your experiment's method now...
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:19 INFO] [activity:161] Action: terminate-app-pod
[2021-04-28 02:33:19 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-28 02:33:19 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:19 DEBUG] [actions:193] Found 3 pods labelled 'app=productpage' in ns default
[2021-04-28 02:33:19 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:19 INFO] [activity:161] Action: terminate-app-pod
[2021-04-28 02:33:19 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-28 02:33:19 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:19 DEBUG] [actions:193] Found 3 pods labelled 'app=productpage' in ns default
[2021-04-28 02:33:19 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:33:19 DEBUG] [run:496] Running steady-state hypothesis after the method
[2021-04-28 02:33:19 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:19 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:19 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:33:19 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:33:19 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:20 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:33:20 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:33:20 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:20 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:33:20 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:33:20 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:20 INFO] [run:809] Let's rollback...
[2021-04-28 02:33:20 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:33:20 INFO] [rollback:25] No declared rollbacks, let's move on.
[2021-04-28 02:33:20 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-28 02:33:20 INFO] [run:421] Experiment ended with status: completed
[2021-04-28 02:33:20 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:33:20 DEBUG] [__init__:72] Cleaning up controls
[2021-04-28 02:33:20 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:33:21 DEBUG] [cli:73] ###############################################################################
[2021-04-28 02:33:21 DEBUG] [cli:74] Running command 'run'
[2021-04-28 02:33:21 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-28 02:33:22 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-28 02:33:22 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:33:22 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-28 02:33:22 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:33:22 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:33:22 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-28 02:33:22 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:33:22 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:33:22 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:33:23 INFO] [experiment:96] Experiment looks valid
[2021-04-28 02:33:23 DEBUG] [caching:42] Clearing activities cache
[2021-04-28 02:33:23 DEBUG] [caching:25] Building activity cache...
[2021-04-28 02:33:23 DEBUG] [caching:35] Cached 2 activities
[2021-04-28 02:33:23 DEBUG] [configuration:54] Loading configuration...
[2021-04-28 02:33:23 DEBUG] [secret:75] Loading secrets...
[2021-04-28 02:33:23 DEBUG] [secret:92] Secrets loaded
[2021-04-28 02:33:23 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-28 02:33:23 DEBUG] [__init__:39] Initializing controls
[2021-04-28 02:33:23 INFO] [run:342] Steady-state strategy: default
[2021-04-28 02:33:23 INFO] [run:345] Rollbacks strategy: default
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:33:23 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-28 02:33:23 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:23 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:33:23 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:33:23 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:23 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-28 02:33:23 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:23 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-28 02:33:23 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:23 INFO] [run:553] Playing your experiment's method now...
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:23 INFO] [activity:161] Action: terminate-app-pod
[2021-04-28 02:33:23 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-28 02:33:23 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:23 DEBUG] [actions:193] Found 3 pods labelled 'app=productpage' in ns default
[2021-04-28 02:33:23 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:23 INFO] [activity:161] Action: terminate-app-pod
[2021-04-28 02:33:23 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-28 02:33:23 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:23 DEBUG] [actions:193] Found 3 pods labelled 'app=productpage' in ns default
[2021-04-28 02:33:23 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-28 02:33:23 DEBUG] [run:496] Running steady-state hypothesis after the method
[2021-04-28 02:33:23 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:23 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-28 02:33:23 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-28 02:33:23 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-28 02:33:23 DEBUG] [probes:277] Found 0 failed and 1 not ready pods
[2021-04-28 02:33:23 DEBUG] [activity:235] Activity failed
[2021-04-28 02:33:23 ERROR] [activity:188]   => failed: chaoslib.exceptions.ActivityFailed: the system is unhealthy
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-28 02:33:23 WARNING] [hypothesis:200] Probe terminated unexpectedly, so its tolerance could not be validated
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-28 02:33:23 CRITICAL] [run:507] Steady state probe 'all-apps-are-healthy' is not in the given tolerance so failing this experiment
[2021-04-28 02:33:23 INFO] [run:421] Experiment ended with status: deviated
[2021-04-28 02:33:23 INFO] [run:423] The steady-state has deviated, a weakness may have been discovered
[2021-04-28 02:33:23 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-28 02:33:23 DEBUG] [__init__:72] Cleaning up controls
[2021-04-28 02:33:23 DEBUG] [caching:42] Clearing activities cache
